@baseUrl = http://localhost:3333

### 1. Criar Tarefa
POST {{baseUrl}}/todos
Content-Type: application/json

{
  "title": "Minha Primeira Tarefa Pública",
  "description": "Funcionou sem login!"
}

### 2. Listar Todas
# Copie o ID que aparecer aqui para usar nos próximos
GET {{baseUrl}}/todos

### 3. Atualizar (Marcar como Feita)
PATCH {{baseUrl}}/todos/019ad027-78ee-74e9-8324-dcd270898d93
Content-Type: application/json

{
  "isDone": true
}

### 4. Deletar
DELETE {{baseUrl}}/todos/019ad027-78ee-74e9-8324-dcd270898d93